services:
  run-itest-currency-exchange:
    container_name: ordermgt-itest-currex-0
    image: ordermgt-with-devtools:latest
    pull_policy: never
    restart: no
    environment:
      - RUST_BACKTRACE=1
      - SYS_BASE_PATH=/app
      - SERVICE_BASE_PATH=/app/order
    working_dir: /app/order
    command: cargo test --release --test unittest --features "mariadb amqprs" -- adapter::thirdparty::currency_exchange --test-threads=1
    volumes:
      - ../tests/unit/examples:/app/order/tests/unit/examples:ro
      - ../../common/data/secrets.json:/app/common/data/secrets.json:ro
      - ../../tmp/log/test:/app/log

