services:
  mariadb-ordermgt:
    image: mariadb:11-noble
    container_name: ordermgt-generic-mariadb
    environment:
      - DB_NAME=ecommerce_order
    ports:
      # Maps port 3306 on the host to port 3307 in the container
      - "3306:3307"
    volumes:
      - ./mariadb-cfg/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh:ro
      # use environment variable interpolation for database storage files
      # Mounts the host directory for persistent data storage.
      # This is a bind mount to a specific path on your host machine.
      - ${MARIADB_DATA_VOL}:/var/lib/mysql
      # mount log / error files for troubleshooting
      - ${MARIADB_LOG_VOL}:/var/log/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping --host=localhost --port=3307 --user=$${SITEDBA_UNAME} --password=$${SITEDBA_PASSWORD} --silent || exit 1"]
      interval: 10s
      timeout: 7s
      retries: 10
      start_period: 35s

  db-schema-migration-up-ordermgt:
    container_name: ordermgt-unknown-db-schema-upgrade
    image: liquibase:4.33-alpine
    profiles:
      - serverstart
      - migrateonly
    restart: no
    volumes:
      - ../migration:/liquibase/changelog:ro
      - ../liquibase.properties:/liquibase/liquibase.properties:ro
    # environment variable expansion is part of shell-specific features, here
    # it is required to explicitly specify which shell to run the command.
    command: ["/bin/sh", "-c", "liquibase --defaults-file=/liquibase/liquibase.properties --url=jdbc:mariadb://$${DB_HOST}:3307/ecommerce_order --username=$${SITEDBA_UNAME} --password=$${SITEDBA_PASSWORD} --search-path=/liquibase/changelog --log-level=info update"]
    depends_on:
      mariadb-ordermgt:
        condition: service_healthy

  db-schema-migration-down-ordermgt:
    container_name: ordermgt-unknown-db-schema-downgrade
    image: liquibase:4.33-alpine
    profiles:
      - cleandbschema
    restart: no
    volumes:
      - ../migration:/liquibase/changelog:ro
      - ../liquibase.properties:/liquibase/liquibase.properties:ro
    command: ["/bin/sh", "-c", "liquibase --defaults-file=/liquibase/liquibase.properties --url=jdbc:mariadb://$${DB_HOST}:3307/ecommerce_order --username=$${SITEDBA_UNAME} --password=$${SITEDBA_PASSWORD} --search-path=/liquibase/changelog --log-level=info  rollback  $${MIGRATE_VERSION_TAG}"]

