# installation suggestion from liquibase official doc :
# https://docs.liquibase.com/start/install/liquibase-linux-debian-ubuntu.html

name: 'install liquibase migration tool'
description: 'install liquibase migration tool'
runs:
    using: 'composite'
    steps:
      - name: 
        shell: bash
        run: |
          wget -O- https://repo.liquibase.com/liquibase.asc | gpg --dearmor > ./liquibase-keyring.gpg
          cat ./liquibase-keyring.gpg | sudo tee /usr/share/keyrings/liquibase-keyring.gpg > /dev/null
          echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/liquibase-keyring.gpg] https://repo.liquibase.com stable main' | sudo tee /etc/apt/sources.list.d/liquibase.list
          sudo apt-get update
          sudo apt-get install liquibase
          liquibase --version
