# Generated by Django 3.1 on 2020-05-27 15:50

from django.db import migrations, models
from common.models.migrations import AlterTablePrivilege


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('country', models.CharField(choices=[('AU', 'Au'), ('CN', 'Cn'), ('CZ', 'Cz'), ('DE', 'De'), ('FR', 'Fr'), ('HK', 'Hk'), ('IT', 'It'), ('IL', 'Il'), ('MY', 'My'), ('NZ', 'Nz'), ('SG', 'Sg'), ('TH', 'Th'), ('TW', 'Tw'), ('US', 'Us')], default='TW', max_length=2)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('road', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=100)),
                ('floor', models.SmallIntegerField(default=1)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]

    def __new__(cls, *args, **kwargs):
        if not hasattr(cls, '_privilege_update_init'):
            cls.operations[0]._priv_lvl = AlterTablePrivilege.PRIVILEGE_MAP['READ_WRITE']
            privilege_update_obj = AlterTablePrivilege( autogen_ops=cls.operations,  db_setup_tag='usermgt_service')
            cls._privilege_update_init = True
        return super().__new__(cls)

