# Generated by Django 3.1 on 2020-06-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='city',
            new_name='locality',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='road',
            new_name='street',
        ),
    ]
