# Generated by Django 3.1 on 2020-07-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20200601_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(choices=[('AU', 'Au'), ('AT', 'At'), ('CZ', 'Cz'), ('DE', 'De'), ('HK', 'Hk'), ('IN', 'In'), ('ID', 'Id'), ('IL', 'Il'), ('MY', 'My'), ('NZ', 'Nz'), ('PT', 'Pt'), ('SG', 'Sg'), ('TH', 'Th'), ('TW', 'Tw'), ('US', 'Us')], default='TW', max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
