# Generated by Django 3.1 on 2020-07-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20200729_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
