[project]
name = "user-management"
version = "0.1.2"
authors = [
    {name="T.H.", email="xxx@somemail.com"}
]
requires-python = ">=3.13"

[tool.setuptools.package-dir]
user_management = "./src"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
