# Generated by Django 3.1 on 2020-06-03 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ####('purchase', '0002_auto_20200603_1142'),
        ####('sale', '0002_auto_20200603_1142'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        ##migrations.DeleteModel(
        ##    name='Employee',
        ##),
    ]
