# Generated by Django 3.1 on 2020-06-03 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericusergroup',
            name='meta_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='genericusergroup',
            name='parent',
            field=models.ForeignKey(db_column='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.genericusergroup'),
        ),
    ]
