# Generated by Django 3.1 on 2020-06-04 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20200603_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericusergroup',
            name='meta_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='genericusergroup',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.genericusergroup'),
        ),
    ]
