# Generated by Django 3.1 on 2020-06-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20200604_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericusergroup',
            name='max_num_addr',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='genericusergroup',
            name='max_num_email',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='genericusergroup',
            name='max_num_phone',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='genericuserprofile',
            name='max_bookings',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='genericuserprofile',
            name='max_entry_waitlist',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='genericuserprofile',
            name='max_num_addr',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='genericuserprofile',
            name='max_num_email',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='genericuserprofile',
            name='max_num_phone',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
