# Generated by Django 3.1 on 2020-06-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20200605_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericusergroup',
            name='parent',
        ),
        migrations.CreateModel(
            name='GenericUserGroupClosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveIntegerField(db_column='depth', default=0)),
                ('ancestor', models.ForeignKey(db_column='ancestor', on_delete=django.db.models.deletion.CASCADE, related_name='ancestor', to='user_management.genericusergroup')),
                ('descendant', models.ForeignKey(db_column='descendant', on_delete=django.db.models.deletion.CASCADE, related_name='descendant', to='user_management.genericusergroup')),
            ],
            options={
                'db_table': 'generic_user_group_closure',
            },
        ),
    ]
