# Generated by Django 3.1 on 2020-06-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_auto_20200628_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericuserprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='generic_user_group_relation', to='user_management.GenericUserGroup'),
        ),
    ]
