# Generated by Django 3.1 on 2020-07-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_genericuserprofile_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericgroupauthrelation',
            name='time_deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='genericusergroup',
            name='time_deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='genericusergroupclosure',
            name='time_deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='genericuserprofile',
            name='time_deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
