# Generated by Django 3.1 on 2020-07-04 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_auto_20200704_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericusergroupclosure',
            name='ancestor',
            field=models.ForeignKey(db_column='ancestor', on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='user_management.genericusergroup'),
        ),
        migrations.AlterField(
            model_name='genericusergroupclosure',
            name='descendant',
            field=models.ForeignKey(db_column='descendant', on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='user_management.genericusergroup'),
        ),
    ]
