# Generated by Django 3.1 on 2020-07-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_auto_20200704_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericusergroup',
            name='max_bookings',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='genericusergroup',
            name='max_entry_waitlist',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='genericusergroup',
            name='max_num_email',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='genericuserprofile',
            name='max_num_email',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
