# Generated by Django 3.1 on 2020-07-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_auto_20200713_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaddress',
            name='domain_name',
        ),
        migrations.RemoveField(
            model_name='emailaddress',
            name='local_part',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='addr',
            field=models.EmailField(default='notprovide@localhost', max_length=160),
        ),
        migrations.AlterField(
            model_name='genericuserprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='genericuserprofile',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
