# Generated by Django 3.1 on 2020-07-31 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_auto_20200731_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuserresetrequest',
            name='hashed_token',
            field=models.BinaryField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='authuserresetrequest',
            name='profile',
            field=models.OneToOneField(blank=True, db_column='profile', on_delete=django.db.models.deletion.CASCADE, to='user_management.genericuserprofile'),
        ),
    ]
