# Generated by Django 3.1 on 2020-08-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_auto_20200802_2335'),
        ('user_management', '0017_auto_20200816_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericusergroup',
            name='roles',
            field=models.ManyToManyField(blank=True, db_table='generic_group_auth_role', related_name='auth_roles', to='auth.Group'),
        ),
    ]
