# Generated by Django 3.1 on 2020-09-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0019_auto_20200821_1532'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='genericusergroupclosure',
            constraint=models.UniqueConstraint(fields=('ancestor', 'descendant'), name='unique_path'),
        ),
    ]
