# Generated by Django 3.1 on 2020-09-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0015_auto_20200819_2141'),
        ('user_management', '0020_auto_20200908_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericuserprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, db_table='generic_user_prof_auth_role', related_name='user_profiles', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='genericusergroup',
            name='roles',
            field=models.ManyToManyField(blank=True, db_table='generic_group_auth_role', related_name='user_groups', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='userquotarelation',
            name='usage_type',
            field=models.ForeignKey(db_column='usage_type', on_delete=django.db.models.deletion.CASCADE, related_name='user_quota_rules', to='user_management.quotausagetype'),
        ),
    ]
