# Generated by Django 3.1 on 2020-09-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_management', '0022_auto_20200909_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotausagetype',
            old_name='name',
            new_name='label',
        ),
        migrations.AddField(
            model_name='quotausagetype',
            name='material',
            field=models.ForeignKey(db_column='material', default=15, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
