# Generated by Django 3.1 on 2020-09-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_management', '0023_auto_20200915_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotausagetype',
            name='material',
            field=models.OneToOneField(db_column='material', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
