# Generated by Django 3.1 on 2020-10-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0024_auto_20200915_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuserresetrequest',
            name='email',
            field=models.ForeignKey(blank=True, db_column='email', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.useremailaddress'),
        ),
    ]
