# Generated by Django 3.1 on 2020-11-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0029_auto_20201105_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphonenumber',
            name='phone',
            field=models.OneToOneField(db_column='phone', on_delete=django.db.models.deletion.CASCADE, to='user_management.phonenumber'),
        ),
    ]
