# Generated by Django 3.1 on 2020-11-09 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0030_auto_20201109_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphonenumber',
            name='phone',
            field=models.OneToOneField(db_column='phone', on_delete=django.db.models.deletion.CASCADE, related_name='userphone', to='user_management.phonenumber'),
        ),
    ]
