# Generated by Django 3.1 on 2020-11-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0031_auto_20201109_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericuserappliedrole',
            name='time_deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='genericusergrouprelation',
            name='time_deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
