# Generated by Django 3.1 on 2020-12-22 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0032_auto_20201112_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericusergroupclosure',
            name='ancestor',
            field=models.ForeignKey(db_column='ancestor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='user_management.genericusergroup'),
        ),
        migrations.AlterField(
            model_name='genericusergroupclosure',
            name='descendant',
            field=models.ForeignKey(db_column='descendant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='user_management.genericusergroup'),
        ),
    ]
