services:
  api-server-storefront:
    container_name: storefront-dev-apisrv
    env_file:
      - ./container-dev.env
    environment:
      - APP_SETTINGS=settings.development
    volumes:
      - ../settings/development.py:/app/store/settings/development.py:ro
      - ../settings/log-cfg-dev.json:/app/store/settings/log-cfg.json:ro
      - ../../common/data/cors-dev.json:/app/common/data/cors.json:ro 
      - ../../common/data/secrets.json:/app/common/data/secrets.json:ro
      - ../../tmp/log/dev:/app/log
    networks:
      - net1
      - net2
      - net3

  rpc-consumer-storefront:
    container_name: storefront-dev-rpcconsumer
    env_file:
      - ./container-dev.env
    environment:
      - SYS_BASE_PATH=/app
      - APP_SETTINGS=settings.development
      - PYTHONPATH=$PYTHONPATH:/app/store/settings
    volumes:
      - ../settings/development.py:/app/store/settings/development.py:ro
      - ../../common/data/cors-dev.json:/app/common/data/cors.json:ro 
      - ../../common/data/secrets.json:/app/common/data/secrets.json:ro
      - ../../tmp/log/dev:/app/log
    networks:
      - net1
      - net2

networks:
  net2:
    name: ec-intersrvs-dev-net
    external: true
  
  net3:
    name: ec-usrmgt-dev-net
    external: true

