services:
  db-schema-migration-codegen-storefront:
    container_name: storefront-dev-db-migrate-codegen
    env_file:
      - ./container-dev.env
    environment:
      - APP_SETTINGS=settings.migration
    volumes:
      - ../settings/migration.py:/app/store/settings/migration.py:ro
      - ../../common/data/cors-dev.json:/app/common/data/cors.json:ro 
      - ../../common/data/secrets.json:/app/common/data/secrets.json:ro
    networks:
      - net1
