x-base-service-common: &reuse-basesrv-cfg
  image: storefront-backend-base:latest
  pull_policy: never
  profiles:
    - serverstart
  restart: no
  environment:
    DB_PORT: 3311
    DB_NAME: ecommerce_store
  stop_signal: SIGTERM
  working_dir: /app/store
  volumes:
    - ../settings/common.py:/app/store/settings/common.py:ro
    - ../settings/celeryconfig.py:/app/store/settings/celeryconfig.py:ro
  depends_on:
    db-schema-migration-up-storefront:
      condition: service_completed_successfully


services:
  mariadb-storefront:
    image: mariadb-ext:11-noble
    container_name: storefront-generic-mariadb
    pull_policy: never
    restart: no
    environment:
      - DB_NAME=ecommerce_store
    ports:
      # Maps port 3310 on the host to port 3311 in the container
      - "3310:3311"
    volumes:
      - ./mariadb-cfg/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh:ro
      - ${MARIADB_DATA_VOL}:/var/lib/mysql
      - ${MARIADB_LOG_VOL}:/var/log/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping --host=localhost --port=3311 --user=$${SITEDBA_UNAME} --password=$${SITEDBA_PASSWORD} --silent || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 40s

  db-schema-migration-up-storefront:
    container_name: storefront-unknown-db-schema-upgrade
    image: storefront-backend-base:latest
    pull_policy: never
    restart: no
    environment:
      - DB_NAME=ecommerce_store
      - DB_PORT=3311
    working_dir: /app/store
    command: alembic --config alembic_app.ini upgrade 000004
    volumes:
      - ../alembic_app.ini:/app/store/alembic_app.ini:ro
      - ../settings/common.py:/app/store/settings/common.py:ro
      - ../settings/celeryconfig.py:/app/store/settings/celeryconfig.py:ro
    depends_on:
      mariadb-storefront:
        condition: service_healthy

  db-schema-migration-down-storefront:
    container_name: storefront-unknown-db-schema-downgrade
    image: storefront-backend-base:latest
    pull_policy: never
    restart: no
    profiles:
      - cleandbschema
    environment:
      - DB_NAME=ecommerce_store
      - DB_PORT=3311
    working_dir: /app/store
    command: ["/bin/sh", "-c", "alembic --config alembic_app.ini downgrade base"]
    volumes:
      - ../alembic_app.ini:/app/store/alembic_app.ini:ro
      - ../settings/common.py:/app/store/settings/common.py:ro
      - ../settings/celeryconfig.py:/app/store/settings/celeryconfig.py:ro

  api-server-storefront:
    <<: *reuse-basesrv-cfg
    container_name: storefront-unknown-apisrv
    command: ["/bin/sh", "-c", "exec uvicorn --host 0.0.0.0 --port 8011 --access-log --log-config ./settings/log-cfg.json store.entry.web:app"]

  rpc-consumer-storefront:
    <<: *reuse-basesrv-cfg
    container_name: storefront-unknown-rpcconsumer
    command: ["/bin/sh", "-c", "exec celery --app=ecommerce_common.util  --config=$${APP_SETTINGS} --workdir ./src  worker --concurrency 1  --loglevel=INFO  --hostname=storefront@%h -E --logfile=/app/log/storefront-rpc-consumer.log"]

