#!/bin/bash

testmodules=("./tests/storeprofile/models.py" "./tests/storeprofile/api.py" "./tests/staff.py" "./tests/business_hours.py" "./tests/products.py")

for module in "${testmodules[@]}"; do
    pytest -v -s "$module"
    exit_code=$?

    if [ $exit_code -ne 0 ]; then
        exit $exit_code
    fi
done
