services:
  elasticsearch:
    container_name: productmgt-dev-elastic
    environment:
      cluster.name: "dev-es-cluster0"
      node.name: "es-dev-node-0"
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms256m -Xmx256m -Dlog4j2.formatMsgNoLookups=true"
      indices.query.bool.max_clause_count: "1025"
      cluster.routing.allocation.disk.watermark.low: "51%"
      cluster.routing.allocation.disk.watermark.high: "75%"
      cluster.routing.allocation.disk.watermark.flood_stage: "80%"
    
    env_file:
      - ./container-dev.env
    networks:
      - net1

    ulimits:
      # localed-in memory space in kilobytes
      memlock:
        soft: 570400
        hard: 572000
      nofile:
        soft: 64000
        hard: 65536
  
  db-schema-migration-prodmgt:
    container_name: productmgt-dev-db-schema-migrate
    env_file:
      - ./container-dev.env
    networks:
      - net1
  
  run-itest-prodmgt:
    container_name: productmgt-itest-0
    image: productmgt-backend-base:latest
    pull_policy: never
    profiles:
      - serverstart
    env_file:
      - ./container-dev.env
    environment:
      APP_SETTINGS: settings.development
    networks:
      - net1
    restart: no
    working_dir: /app/productmgt/v2.x
    volumes:
      - ./run_integration_test:/app/entry/run_my_app
      - ../settings/development.py:/app/productmgt/v2.x/settings/development.py
      - ../settings/elastic_curator.yaml:/app/productmgt/v2.x/settings/elastic_curator.yaml
      - ../settings/celeryconfig.py:/app/productmgt/v2.x/settings/celeryconfig.py
      - ../tests/integration:/app/productmgt/v2.x/tests/integration
      - ../../../common/data/secrets.json:/app/common/data/secrets.json:ro
      - ../../../common/data/cors-dev.json:/app/common/data/cors.json:ro
      - ../../../tmp/cache/dev/jwks:/app/tmp/cache/dev/jwks
    depends_on:
      db-schema-migration-prodmgt:
        condition: service_completed_successfully

  api-server-prodmgt:
    container_name: productmgt-dev-apisrv
    env_file:
      - ./container-dev.env
    environment:
      APP_SETTINGS: settings.development
    stop_signal: SIGTERM
    stop_grace_period: 15s
    volumes:
      - ../settings/development.py:/app/productmgt/v2.x/settings/development.py:ro
      - ../settings/log-cfg-dev.json:/app/productmgt/v2.x/settings/log-cfg.json:ro
      - ../../../common/data/secrets.json:/app/common/data/secrets.json:ro
      - ../../../common/data/cors-dev.json:/app/common/data/cors.json:ro
      - ../../../tmp/log/dev:/app/log
    depends_on:
      run-itest-prodmgt:
        condition: service_completed_successfully
    networks:
      - net1
      - net2

  rpc-consumer-prodmgt:
    container_name: productmgt-dev-rpcconsumer
    env_file:
      - ./container-dev.env
    environment:
      APP_SETTINGS: settings.development
    stop_signal: SIGTERM
    stop_grace_period: 20s
    volumes:
      - ../settings/development.py:/app/productmgt/v2.x/settings/development.py:ro
      - ../settings/celeryconfig.py:/app/productmgt/v2.x/settings/celeryconfig.py
      - ../../../common/data/secrets.json:/app/common/data/secrets.json:ro
      - ../../../common/data/cors-dev.json:/app/common/data/cors.json:ro
      - ../../../tmp/log/dev:/app/log
    depends_on:
      run-itest-prodmgt:
        condition: service_completed_successfully
    networks:
      - net1
      - net3

  authgen-smoketest-prodmgt:
    container_name: productmgt-dev-auth4smoketest
    image: usrmgt-backend-base:latest
    pull_policy: never
    profiles:
      - serverstart
    restart: no
    env_file:
      - ../../../user_management/infra/container-dev.env
    environment:
      - DB_NAME=ecommerce_usermgt
      - DB_PORT=3307
      - API_HOST=usrmgt-dev-apisrv
      - API_PORT=8008
      - APP_USER_ID=113
    working_dir: /app/usermgt
    command: python3 -m tests.gen_jwt_smoketest
    volumes:
      - ../tests/gen_jwt_smoketest.py:/app/usermgt/tests/gen_jwt_smoketest.py
      - ../../../common/data/secrets.json:/app/common/data/secrets.json:ro
      - ../../../common/data/cors-dev.json:/app/common/data/cors.json:ro
      - ../../../user_management/settings/common.py:/app/usermgt/settings/common.py:ro
      - ../../../user_management/settings/development.py:/app/usermgt/settings/development.py:ro
      - ../../../user_management/tests/standalone_env_setup.py:/app/usermgt/tests/standalone_env_setup.py
      - ../../../tmp/log/dev:/app/tmp/log/dev
      - ../../../tmp/cache/dev/jwks:/app/tmp/cache/dev/jwks:ro
    networks:
      - net2

  smoke-test-prodmgt:
    container_name: productmgt-dev-smoketest
    image: productmgt-backend-base:latest
    pull_policy: never
    profiles:
      - serverstart
    restart: no
    env_file:
      - ./container-dev.env
    environment:
      - API_HOST=productmgt-dev-apisrv
      - API_PORT=8009
      - APP_USER_ID=113
      - APP_SETTINGS=settings.development
    working_dir: /app/productmgt/v2.x
    command: python3 -m tests.smoke_test
    volumes:
      - ../tests/smoke_test.py:/app/productmgt/v2.x/tests/smoke_test.py:ro
      - ../settings/common.py:/app/productmgt/v2.x/settings/common.py:ro
      - ../settings/development.py:/app/productmgt/v2.x/settings/development.py:ro
      - ../settings/celeryconfig.py:/app/productmgt/v2.x/settings/celeryconfig.py:ro
      - ../../../common/data/secrets.json:/app/common/data/secrets.json:ro
      - ../../../tmp/log/dev:/app/log
    depends_on:
      authgen-smoketest-prodmgt:
        condition: service_completed_successfully
      api-server-prodmgt:
        condition: service_started
      rpc-consumer-prodmgt:
        condition: service_started
    networks:
      - net1
      - net2
      - net3


networks:
  net1:
    name: ec-productmgt-dev-net
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.5.0/24
          ip_range: 172.19.5.0/25
          gateway: 172.19.5.254
  net2:
    name: ec-usrmgt-dev-net
    external: true
  net3:
    name: ec-intersrvs-dev-net
    external: true
