#!/bin/bash

testmodules=("./tests/integration/tag.py" "./tests/integration/attribute.py" "./tests/integration/saleable_item.py")

for module in "${testmodules[@]}"; do
    pytest -v -s "$module"
    exit_code=$?

    if [ $exit_code -ne 0 ]; then
        exit $exit_code
    fi
done
