# Generated by Django 3.1 on 2021-10-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericuserappliedrole',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='genericuserappliedrole',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquotarelation',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquotarelation',
            name='time_deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
