# Note , docker does not support reference block configuration
# across different files
services:
  mariadb:
    container_name: usrmgt-dev-mariadb
    env_file:
      - ./dev.env
    restart: on-failure:3
    stop_grace_period: 40s
    volumes:
      # Mounts the custom configuration file into the container.
      # The source path is relative to this compose file.
      - ./mariadb-cfg/usrmgt-dev.cnf:/etc/mysql/conf.d/usrmgt.cnf:ro      
      # Mounts the host directory for persistent data storage.
      # This is a bind mount to a specific path on your host machine.
      - /data/db/dev/mariadb/e-comm/usrmgt:/var/lib/mysql
      # mount log / error files for troubleshooting
      - /var/log/mariadb/dev/e-comm/usrmgt:/var/log/mysql
    networks:
      - net11

  db-schema-migration:
    container_name: usrmgt-dev-db-schema-migrate
    env_file:
      - ./dev.env
    volumes:
      - ../../common/data/cors-dev.json:/app/common/data/cors.json:ro
    networks:
      - net11

  db-initial-data-import:
    container_name: usrmgt-dev-db-data-migrate
    env_file:
      - ./dev.env
    volumes:
      - ../../common/data/cors-dev.json:/app/common/data/cors.json:ro
    networks:
      - net11

  api-server:
    container_name: usrmgt-dev-apisrv
    env_file:
      - ./dev.env
    restart: no
    #on-failure:2
    # Django server recognizes only SIGINT as shutdown signal
    stop_signal: SIGINT
    stop_grace_period: 1m15s
    volumes:
      - ./api_server_dev:/app/entry/run_my_app
      - ../../common/data/cors-dev.json:/app/common/data/cors.json:ro
      - ../../tmp/log/dev:/app/tmp/log/dev
      - ../../tmp/cache/dev/jwks:/app/tmp/cache/dev/jwks:ro
    networks:
      - net11
      - net12

  rpc-consumer:
    container_name: usrmgt-dev-rpcconsumer
    env_file:
      - ./dev.env
    environment:
      - DJANGO_SETTINGS_MODULE=settings.development
    restart: no
    stop_grace_period: 18s
    volumes:
      - ./run_rpc_consumer:/app/entry/run_my_app
      - ../../common/data/cors-dev.json:/app/common/data/cors.json:ro
      - ../../tmp/log/dev:/app/log
      - ../../tmp/cache/dev/jwks:/app/tmp/cache/dev/jwks
    networks:
      - net11
      - net12

  smoke-test:
    container_name: usrmgt-dev-smoketest
    image: usrmgt-backend-base:latest
    pull_policy: never
    env_file:
      - ./dev.env
    environment:
      - DB_NAME=ecommerce_usermgt
      - DB_PORT=3307
      - API_HOST=usrmgt-dev-apisrv
      - API_PORT=8008
    restart: no
    volumes:
      - ../tests/smoke_test.py:/app/usermgt/tests/smoke_test.py:ro
      - ../../common/data/secrets.json:/app/common/data/secrets.json:ro
      - ../../common/data/cors-dev.json:/app/common/data/cors.json:ro
    working_dir: /app/usermgt
    command: pipenv run python3 -m tests.smoke_test
    profiles:
      - initialstart
      - serverstart
    depends_on:
      db-initial-data-import:
        condition: service_completed_successfully
      api-server:
        condition: service_started
      rpc-consumer:
        condition: service_started
    networks:
      - net11

networks:
  net11:
    name: ec-usrmgt-dev-net
    external: false
    ipam:
      config:
        - subnet: 172.19.2.0/24
          ip_range: 172.19.2.0/25
          gateway: 172.19.2.254
  net12:
    name: ec-intersrvs-dev-net
    external: true

