x-base-service-common: &reuse-basesrv-cfg
  image: usrmgt-backend-base:latest
  # only consider images existing in local machine, do not pull from remote sites
  pull_policy: never
  restart: no
  environment: &common-env
    DB_NAME: ecommerce_usermgt
    DB_PORT: 3307
  volumes:
    - ../settings/common.py:/app/usermgt/settings/common.py:ro
    - ../../common/data/secrets.json:/app/common/data/secrets.json:ro
    # TODO, switch to Docker Secret or Vault for better security
  
services:
  mariadb-usrmgt:
    # options can be overwritten by successive docker compose file for
    # multiple runtime environments, e.g. dev / test / production
    image: mariadb-ext:11-noble
    container_name: usrmgt-generic-mariadb
    environment:
      - DB_NAME=ecommerce_usermgt
    ports:
      # Maps port 3306 on the host to port 3307 in the container
      - "3306:3307"
    volumes:
      - ./mariadb-cfg/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh:ro
      # use environment variable interpolation for database storage files
      # Mounts the host directory for persistent data storage.
      # This is a bind mount to a specific path on your host machine.
      - ${MARIADB_DATA_VOL}:/var/lib/mysql
      # mount log / error files for troubleshooting
      - ${MARIADB_LOG_VOL}:/var/log/mysql
  
  db-schema-migration-usrmgt:
    <<: *reuse-basesrv-cfg
    container_name: usrmgt-unknown-db-schema-migrate
    profiles:
      - serverstart
      - migrateonly
    working_dir: /app/usermgt
    volumes:
      # volumes from anchor `x-base-service-common` will be replaced with
      # items below, not merged into the volume set here.
      - ./db_schema_migration:/app/entry/run_my_app
      - ../settings/common.py:/app/usermgt/settings/common.py:ro
      - ../../common/data/secrets.json:/app/common/data/secrets.json:ro
    depends_on:
      # condition cannot be specified here because mariaDB container requires extra time to
      # get real database server ready for accepting inbound connections , neither
      # `service_started` or `service_completed_successfully` fits in such case.
      - mariadb-usrmgt
  
  db-initial-data-import-usrmgt:
    <<: *reuse-basesrv-cfg
    container_name: usrmgt-unknown-db-data-migrate
    profiles:
      - initialstart
      - migrateonly
    working_dir: /app/usermgt
    volumes:
      - ./db_init_data_migration:/app/entry/run_my_app
      - ../settings/common.py:/app/usermgt/settings/common.py:ro
      - ../../common/data/secrets.json:/app/common/data/secrets.json:ro
    depends_on:
      db-schema-migration-usrmgt:
        condition: service_completed_successfully

  api-server-usrmgt:
    <<: *reuse-basesrv-cfg
    container_name: usrmgt-unknown-apisrv
    ports:
      - "8008:8008"
    profiles:
      - serverstart
    healthcheck:
      test: ["CMD-SHELL", "python3 -m ecommerce_common.util.httpsrv_accessible --timeout-secs=8 --host=localhost --port=8008 --uri-path=/jwks"]
      interval: 90s
      timeout: 6s
      retries: 2
      start_period: 18s
    depends_on:
      db-schema-migration-usrmgt:
        condition: service_completed_successfully

  rpc-consumer-usrmgt:
    container_name: usrmgt-unknown-rpcconsumer
    <<: *reuse-basesrv-cfg
    environment:
      <<: *common-env
      SYS_BASE_PATH: /app
    profiles:
      - serverstart
    depends_on:
      db-schema-migration-usrmgt:
        condition: service_completed_successfully

