x-base-service-common: &reuse-basesrv-cfg
  image: usrmgt-backend-base:latest
  # only consider images existing in local machine, do not pull from remote sites
  pull_policy: never
  restart: no
  environment: &common-env
    DB_NAME: ecommerce_usermgt
    DB_PORT: 3307
  volumes:
    - ../settings/common.py:/app/usermgt/settings/common.py:ro
    - ../../common/data/secrets.json:/app/common/data/secrets.json:ro
    # TODO, switch to Docker Secret or Vault for better security
  
services:
  mariadb:
    # options can be overwritten by successive docker compose file for
    # multiple runtime environments, e.g. dev / test / production
    image: mariadb:11-noble
    container_name: usrmgt-generic-mariadb
    environment:
      - DB_NAME=ecommerce_usermgt
    ports:
      # Maps port 3306 on the host to port 3307 in the container
      - "3306:3307"
    volumes:
      - ./mariadb-cfg/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh:ro
  
  db-schema-migration:
    <<: *reuse-basesrv-cfg
    container_name: usrmgt-unknown-db-schema-migrate
    profiles:
      - serverstart
    working_dir: /app/usermgt
    volumes:
      # volumes from anchor `x-base-service-common` will be replaced with
      # items below, not merged into the volume set here.
      - ./db_schema_migration:/app/entry/run_my_app
      - ../settings/common.py:/app/usermgt/settings/common.py:ro
      - ../../common/data/secrets.json:/app/common/data/secrets.json:ro
    depends_on:
      # condition cannot be specified here because mariaDB container requires extra time to
      # get real database server ready for accepting inbound connections , neither
      # `service_started` or `service_completed_successfully` fits in such case.
      - mariadb
  
  db-initial-data-import:
    <<: *reuse-basesrv-cfg
    container_name: usrmgt-unknown-db-data-migrate
    profiles:
      - initialstart
    working_dir: /app/usermgt
    volumes:
      - ./db_init_data_migration:/app/entry/run_my_app
      - ../settings/common.py:/app/usermgt/settings/common.py:ro
      - ../../common/data/secrets.json:/app/common/data/secrets.json:ro
    depends_on:
      db-schema-migration:
        condition: service_completed_successfully

  api-server:
    <<: *reuse-basesrv-cfg
    container_name: usrmgt-unknown-apisrv
    ports:
      - "8008:8008"
    profiles:
      - serverstart
    depends_on:
      db-schema-migration:
        condition: service_completed_successfully

  rpc-consumer:
    container_name: usrmgt-unknown-rpcconsumer
    <<: *reuse-basesrv-cfg
    environment:
      <<: *common-env
      SYS_BASE_PATH: /app
    profiles:
      - serverstart
    depends_on:
      db-schema-migration:
        condition: service_completed_successfully

