services:
  mariadb:
    container_name: usrmgt-test-mariadb
    env_file:
      - ./test.env
    restart: no
    networks:
      - net1
    volumes:
      # Mounts the custom configuration file into the container.
      # The source path is relative to this compose file.
      - ./mariadb-cfg/usrmgt-test.cnf:/etc/mysql/conf.d/usrmgt.cnf:ro      
      # Mounts the host directory for persistent data storage.
      # This is a bind mount to a specific path on your host machine.
      - /data/db/test/mariadb/e-comm/usrmgt:/var/lib/mysql
      # mount log / error files for troubleshooting
      - /var/log/mariadb/test/e-comm/usrmgt:/var/log/mysql
  
  run-test:
    container_name: usrmgt-backend-testapp-0
    image: usrmgt-backend-base:latest
    pull_policy: never
    env_file:
      - ./test.env
    restart: no
    volumes:
      - ./run_test_container:/app/entry/run_my_app
      - ../tests:/app/usermgt/tests:ro
      - ../settings/common.py:/app/usermgt/settings/common.py:ro
      - ../settings/test.py:/app/usermgt/settings/test.py:ro
      - ../../common/data/cors-test.json:/app/common/data/cors.json:ro
      - ../../common/data/secrets.json:/app/common/data/secrets.json:ro
      - ../../common/python/tests/gmail-crt-chain.pem:/app/common/python/tests/gmail-crt-chain.pem:ro
    depends_on:
      mariadb:
        condition: service_started
    networks:
      - net1

networks:
  net1:
    name: ec-usrmgt-test-net
    # auto-create network on start the containers,
    # auto-delete it on stop (and no other containers are attached to the network)
    external: false
    ipam:
      config:
        - subnet: 172.19.1.0/24
          ip_range: 172.19.1.0/25
          gateway: 172.19.1.254

