#!/bin/bash

mkdir -p /app/$APP_LOG_PATH/

python -m unittest tests.keystore.keygen  -v
python -m unittest tests.keystore.persistence  -v
python -m unittest tests.keystore.manager  -v

testmodules=(
    "tests.middlewares.cors" "tests.middlewares.csrf" "tests.util"
    "tests.login" "tests.role.views" "tests.group.models" "tests.group.serializers"
    "tests.group.views" "tests.profile.models" "tests.profile.serializers" "tests.profile.views"
    "tests.account.models" "tests.account.serializers" "tests.account.views" "tests.async_tasks"
)

for module in "${testmodules[@]}"; do
    python ./manage.py test $module  --settings settings.test --keepdb --verbosity=2
    exit_code=$?

    if [ $exit_code -ne 0 ]; then
        exit $exit_code
    fi
done
