# Generated by Django 3.1 on 2021-10-07 07:43
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE TABLE `unauth_reset_account_request` ( `hashed_token` longblob NOT NULL, `time_created` datetime(6) NOT NULL, `email` int(11) NOT NULL, PRIMARY KEY (`hashed_token`(32)), KEY `account_reset_request_email_6d24344f_fk_email_address_id` (`email`),  CONSTRAINT `account_reset_request_email_6d24344f_fk_email_address_id` FOREIGN KEY (`email`) REFERENCES `email_address` (`id`)  )  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin",
            reverse_sql="DROP TABLE `unauth_reset_account_request`",
        ),
    ]

