# Generated by Django 5.2.6 on 2025-09-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_management', '0002_rawsqls'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericUserAppliedRole',
            fields=[
                ('time_deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('user_id', models.PositiveIntegerField(db_column='user_id')),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('pk', models.CompositePrimaryKey('user_type_id', 'user_id', 'role_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_role', to='user_management.genericuserprofile')),
                ('role', models.ForeignKey(db_column='role', on_delete=django.db.models.deletion.CASCADE, related_name='users_applied', to='user_management.role')),
                ('user_type', models.ForeignKey(db_column='user_type', limit_choices_to=models.Q(models.Q(('app_label', 'user_management'), ('model', 'GenericUserProfile')), models.Q(('app_label', 'user_management'), ('model', 'GenericUserGroup')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'generic_user_applied_role',
            },
        ),
        migrations.CreateModel(
            name='GenericUserGroupRelation',
            fields=[
                ('time_deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('pk', models.CompositePrimaryKey('group_id', 'profile_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_group', to='user_management.genericuserprofile')),
                ('group', models.ForeignKey(db_column='group', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='user_management.genericusergroup')),
                ('profile', models.ForeignKey(db_column='profile', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='user_management.genericuserprofile')),
            ],
            options={
                'db_table': 'generic_user_group_relation',
            },
        ),
        migrations.CreateModel(
            name='UserQuotaRelation',
            fields=[
                ('time_deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('user_id', models.PositiveIntegerField(db_column='user_id')),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('pk', models.CompositePrimaryKey('user_type_id', 'user_id', 'material_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('maxnum', models.PositiveSmallIntegerField(default=1)),
                ('material', models.ForeignKey(db_column='material', on_delete=django.db.models.deletion.CASCADE, related_name='usr_relations', to='user_management.quotamaterial')),
                ('user_type', models.ForeignKey(db_column='user_type', limit_choices_to=models.Q(models.Q(('app_label', 'user_management'), ('model', 'GenericUserProfile')), models.Q(('app_label', 'user_management'), ('model', 'GenericUserGroup')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'user_quota_relation',
            },
        ),
    ]
