"""modify_product_id_64b

Revision ID: 000005
Revises: 000004
Create Date: 2025-09-23 17:15:15.840761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '000005'
down_revision = '000004'
branch_labels = None
depends_on = '000004'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_product_available', 'product_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_product_available', 'product_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(display_width=10, unsigned=True),
               existing_nullable=False)
    # ### end Alembic commands ###
