"""
Django settings for restaurant project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os
from pathlib import Path
from datetime import time
# set ExtendedLogger as default logger
from common.logging.logger import ExtendedLogger


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # configure each application by subclassing AppConfig in apps.py of
    # each application folder, give dotted path of the subclass at here
    # to complete application registry.
    'rest_framework',
    'softdelete.apps.SoftdeleteConfig',
    'location.apps.LocationConfig',
    'user_management.apps.UserManagementConfig',
]

# TODO, apply domain name filter at IP layer, only accept requests from trusted proxy server
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'user_management.urls'

TEMPLATES = []

FIXTURE_DIRS = ['my_fixtures',]

# referenced only by development server (`runserver` command)
WSGI_APPLICATION = 'common.util.python.django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = { # will be update with secrets at the bottom of file
    'default': { # only give minimal privilege to start django app server
        'ENGINE': 'django.db.backends.mysql',
        'CONN_MAX_AGE': 0, # set 0 only for debugging purpose
        'TEST': {'NAME': 'test_Restaurant__app_usermgt'}
    },
    'site_dba': { # apply this setup only when you run management commands at backend server
        'ENGINE': 'django.db.backends.mysql',
        'CONN_MAX_AGE': 0,
    },
    'usermgt_service': {
        'ENGINE': 'django.db.backends.mysql',
        'CONN_MAX_AGE': 0,
        'reversed_app_label': ['user_management', 'auth', 'location']
    },
} # end of database settings

DATABASE_ROUTERS = ['common.models.db.ServiceModelRouter']


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = ['common.auth.backends.ForwardClientBackend']


CACHES = {
        'default': {
            'TIMEOUT': 3600,
            'OPTIONS': {
                'MAX_ENTRIES': 512,
                # TODO, figure out how to use KEY_PREFIX and KEY_FUNCTION
                },
            },
        'log_level_change': {
            'TIMEOUT': None,
            'OPTIONS': {
                'MAX_ENTRIES': 1024,
                },
            },
}

AUTH_KEYSTORE = {
    'keystore': 'common.auth.keystore.BaseAuthKeyStore',
    'persist_secret_handler': {
        'module_path': 'common.auth.keystore.JWKSFilePersistHandler',
        'init_kwargs': {
            'filepath': './tmp/cache/production/jwks/privkey/current.json',
            'name':'secret', 'expired_after_days': 7,
        },
    },
    'persist_pubkey_handler': {
        'module_path': 'common.auth.keystore.JWKSFilePersistHandler',
        'init_kwargs': {
            'filepath': './tmp/cache/production/jwks/pubkey/current.json',
            'name':'pubkey', 'expired_after_days': 21,
        },
    },
}

JWT_REMOTE_ACCESS_TOKEN_VALID_PERIOD = 660


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


DATA_UPLOAD_MAX_NUMBER_FIELDS = 400


# use bcrypt + SHA256 as default password hashing function.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]

# logging
_LOG_BASE_DIR = os.path.join(BASE_DIR ,'tmp/log/staffsite')
_LOG_FMT_DBG_BASE = ["{asctime}", "{levelname}", "{process:d}", "{thread:d}", "{pathname}", "{lineno:d}", "{message}"]
_LOG_FMT_DBG_VIEW = ["{req_ip}", "{req_mthd}", "{uri}"] + _LOG_FMT_DBG_BASE


LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'shortened_fmt': {
                'format': "%(asctime)s %(levelname)s %(name)s %(lineno)d %(message)s",
            },
            'dbg_base_fmt': {
                'format': ' '.join(_LOG_FMT_DBG_BASE),
                'style': '{',
            },
            'dbg_view_fmt': {
                'format': ' '.join(_LOG_FMT_DBG_VIEW),
                'style': '{',
            },
        },
        # pre-defined handler classes applied to this project
        'handlers': {
            #'console': {
            #    'level': 'ERROR',
            #    'formatter': 'shortened_fmt',
            #    'class': 'logging.StreamHandler',
            #    'stream': 'ext://sys.stdout',
            #},
            "default_file": {
                'level': 'WARNING',
                'formatter': 'shortened_fmt',
                'class': 'logging.handlers.TimedRotatingFileHandler',
                'filename': str(os.path.join(_LOG_BASE_DIR, 'default.log')),
                # daily log, keep all log files for one year
                'backupCount': 366,
                # new file is created every 0 am (local time)
                'atTime': time(hour=0, minute=0, second=0),
                'encoding': 'utf-8',
                'delay': True, # lazy creation
            },
            "dbg_views_file": {
                'level': 'INFO',
                'formatter': 'dbg_view_fmt',
                'class': 'logging.handlers.TimedRotatingFileHandler',
                'filename': str(os.path.join(_LOG_BASE_DIR, 'views.log')),
                'backupCount': 150,
                'atTime': time(hour=0, minute=0, second=0),
                'encoding': 'utf-8',
                'delay': True, # lazy creation
            },
            "dbg_views_logstash": {
                'level': 'DEBUG',
                'formatter': 'dbg_view_fmt',
                'class':    'logstash_async.handler.AsynchronousLogstashHandler',
                'transport':'logstash_async.transport.TcpTransport',
                'host': 'localhost',
                'port': 5959,
                'database_path': None,
                # In this project logstash input server and django server are hosted in the
                # same machine, therefore it's not necessary to enable secure connection.
                'ssl_enable': False,
            },
            "dbg_base_logstash": {
                'level': 'DEBUG',
                'formatter': 'dbg_base_fmt',
                'class':    'logstash_async.handler.AsynchronousLogstashHandler',
                'transport':'logstash_async.transport.TcpTransport',
                'host': 'localhost',
                'port': 5959,
                'database_path': None,
                'ssl_enable': False,
            },
        }, # end of handlers section
        'loggers': {
            'common.views.api': {
                'level': 'INFO',
                'handlers': ['dbg_views_file', 'dbg_views_logstash'],
            },
            'common.views.mixins': {
                'level': 'INFO',
                'handlers': ['dbg_views_file', 'dbg_views_logstash'],
            },
            'common.views.filters': {
                'level': 'WARNING',
                'handlers': ['dbg_views_logstash'],
            },
            'common.serializers': {
                'level': 'INFO',
                'handlers': ['dbg_base_logstash'],
            },
            'common.serializers.mixins.nested': {
                'level': 'WARNING',
                'handlers': ['dbg_base_logstash'],
            },
            'common.serializers.mixins.quota': {
                'level': 'WARNING',
                'handlers': ['dbg_base_logstash'],
            },
            'common.serializers.mixins.closure_table': {
                'level': 'WARNING',
                'handlers': ['dbg_base_logstash'],
            },
            'common.validators': {
                'level': 'WARNING',
                'handlers': ['dbg_base_logstash'],
            },
            'common.models.closure_table': {
                'level': 'WARNING',
                'handlers': ['dbg_base_logstash'],
            },
            'common.models.db': {
                'level': 'INFO',
                'handlers': ['dbg_base_logstash'],
            },
            'common.models.migrations': {
                'level': 'INFO',
                'handlers': ['default_file', 'dbg_base_logstash'],
            },
            'common.auth.keystore': {
                'level': 'INFO',
                'handlers': ['dbg_base_logstash'],
            },
            'common.auth.backends': {
                'level': 'WARNING',
                'handlers': ['dbg_base_logstash'],
            },
            'common.sessions.middleware': {
                'level': 'WARNING',
                'handlers': ['dbg_base_logstash'],
            },
            'common.sessions.serializers': {
                'level': 'ERROR',
                'handlers': ['dbg_base_logstash'],
            },
            'common.util.python.elasticsearch': {
                'level': 'WARNING',
                'handlers': ['dbg_base_logstash'],
            },
            'common.util.python.async_tasks': {
                'level': 'INFO',
                'handlers': ['dbg_base_logstash'],
            },
            'user_management.views.api': {
                'level': 'INFO',
                'handlers': ['dbg_views_file', 'dbg_views_logstash'],
            },
            'user_management.views.common': {
                'level': 'WARNING',
                'handlers': ['dbg_views_logstash'],
            },
            'user_management.serializers.nested': {
                'level': 'INFO',
                'handlers': ['dbg_base_logstash'],
            },
            'user_management.serializers': {
                'level': 'INFO',
                'handlers': ['dbg_base_logstash'],
            },
            'user_management.models': {
                'level': 'INFO',
                'handlers': ['dbg_base_logstash'],
            },
            'user_management.permissions': {
                'level': 'WARNING',
                'handlers': ['dbg_views_logstash'],
            },
            'user_management.async_tasks': {
                'level': 'INFO',
                'handlers': ['dbg_base_logstash'],
            },
            'user_management.queryset': {
                'level': 'WARNING',
                'handlers': ['dbg_base_logstash'],
            },
            'softdelete.models': {
                'level': 'WARNING',
                'handlers': ['dbg_base_logstash'],
            },
            'softdelete.views': {
                'level': 'INFO',
                'handlers': ['dbg_views_logstash'],
            },
        }, # end of loggers section
        'root': {
            'level': 'ERROR',
            'handlers': ['default_file'],
        },
} # end of LOGGING


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'EXCEPTION_HANDLER': 'common.views.api.exception_handler',
    #'PAGE_SIZE' : 40
}



# mailing function setup
DEFAULT_FROM_EMAIL = 'system@yourproject.io'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True



from common.util.python.django.setup  import setup_secrets

setup_secrets(
    secrets_path='./common/data/secrets.json', module_path=__name__,
    portal_type='staff', interface_type='usermgt'
)

