
name: 'initial setup in RabbitMQ'
description: 'initial setup in RabbitMQ'
inputs:
  vhost:
    description: 'vhost'
    required: true
  uname:
    description: 'username of rabbitMQ account'
    required: true
  passwd:
    description: 'password of the corresponding account'
    required: true
runs:
    using: 'composite'
    steps:
      - name: setup VHost, permissions, and exchange
        shell: bash
        run: |
          CONTAINER_ID=$(docker ps -q --filter "ancestor=rabbitmq:3-management")
          # Verify rabbitmqctl is Available
          docker exec $CONTAINER_ID  rabbitmqctl status
          docker exec $CONTAINER_ID  rabbitmqctl set_permissions -p ${{ inputs.vhost }}  ${{ inputs.uname }}  ".*" ".*" ".*"
          docker exec $CONTAINER_ID  rabbitmqctl list_vhosts
          docker exec $CONTAINER_ID  rabbitmqctl list_permissions -p ${{ inputs.vhost }}
          docker exec $CONTAINER_ID  rabbitmqadmin declare exchange  name=rpc-default-allapps  type=direct \
              durable=true  --vhost=${{ inputs.vhost }}  -u ${{ inputs.uname }} -p ${{ inputs.passwd }}
          docker exec $CONTAINER_ID  rabbitmqctl list_exchanges -p ${{ inputs.vhost }}

