name: experiment MariaDB local init

on:
  push:
    branches: ["experiment-github-action"]

jobs:
  init-env:
    runs-on: ubuntu-24.04
    services:
      mariadb_primary:
        image: mariadb:11.2.6
        ports:
          - 3307:3306
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 0
          MARIADB_ROOT_PASSWORD: "syscidba"
          MARIADB_ROOT_HOST: "localhost"
          MARIADB_DATABASE: "test_db_whatever"
          MARIADB_USER: "DB_USERNAME"
          MARIADB_PASSWORD: "DB_PASSWORD"

    steps:
      - uses: actions/checkout@v4 # checkout codebase from github
      - name: Copy SQL File to Container then Restart MariaDB Service
        run: |
          echo ${{ github.workspace }} 
          ls -lt
          CONTAINER_ID=$(docker ps --filter "ancestor=mariadb:11.2.6" --format "{{.ID}}")
          docker cp ${{ github.workspace }}/experiment-init.sql  $CONTAINER_ID:/docker-entrypoint-initdb.d/
          docker restart $CONTAINER_ID
          sleep 5

      - name: Verify Secondary Database Creation
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-client
          mariadb -h 127.0.0.1 -P 3307 --protocol=TCP -uDB_USERNAME -pDB_PASSWORD -e "CREATE DATABASE test_db_whatever_replica2  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;"
          mariadb -h 127.0.0.1 -P 3307 --protocol=TCP -uDB_USERNAME -pDB_PASSWORD -e "SHOW DATABASES;"
