name: experiment MariaDB local init

on:
  push:
    branches: ["experiment-github-action"]

jobs:
  init-env:
    runs-on: ubuntu-24.04
    services:
      mariadb_primary:
        image: mariadb:11.2.6
        ports:
          - 3307:3306
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 0
          MARIADB_ROOT_PASSWORD: "syscidba"
          MARIADB_ROOT_HOST: "localhost"
          MARIADB_DATABASE: "test_db_whatever"
          MARIADB_USER: "DB_USERNAME"
          MARIADB_PASSWORD: "DB_PASSWORD"
        volumes:
          - .github/workflow/experiment-init.sql

    steps:
    - name: tools installation
      run: |
        ls -lt ./

