name: experiment MariaDB local init

on:
  push:
    branches: ["experiment-github-action"]

jobs:
  init-env:
    runs-on: ubuntu-24.04
    steps:
    - name: tools installation
      run: |
        sudo apt-get update
        sudo apt-get install mariadb-server-11.2
        sudo apt-get install mariadb-client-11.2


