name: experiment MariaDB local init

on:
  push:
    branches: ["experiment-github-action"]

jobs:
  init-env:
    runs-on: ubuntu-24.04
    steps:
    - name: tools installation
      run: |
        MARIADB_VERSION=1:11.2.6+maria~ubu2204
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends mariadb-server="$MARIADB_VERSION"
        sudo apt-get install -y --no-install-recommends mariadb-client="$MARIADB_VERSION"


