name: product management continuous integration
on:
  push:
    branches:
      - 'product-mgt-dev/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/productmgt-ci.yaml'
      - 'services/common/python/**'
      - 'services/product/v2/**'


# due to this long-time unresolved issue, it is safe to put tasks into one
# big job running sequentially, and give up nicely running simulteneous jobs.
# https://github.com/actions/checkout/issues/19
jobs:
    init-env-then-tests:
      runs-on: ubuntu-24.04
      services:
        elasticsearch_v6.8:
          image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
          ports: ['9200:9200']
          options: --env cluster.name=my-ecomm-app  --env "network.host=127.0.0.1" --env bootstrap.memory_lock=true  --env "ES_JAVA_OPTS=-Xms256m -Xmx256m -Xss2m"  --ulimit memlock=-1:-1

      steps:
      - name: check elasticsearch indices
        run: |
            sleep  10
            curl   --request  GET -v  "http://localhost:9200/_cat/indices?v&pretty&format=text&h=health,status,index,pri,rep,docs.count,docs.deleted,store.size,pri.store.size"

      - uses: actions/checkout@v4 # checkout codebase from github

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7
      - name: Install init poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.4

      - name: install dependency packages
        env:
            POETRY_EXPERIMENTAL_SYSTEM_GIT_CLIENT: true
        working-directory: services/product/v2
        run: |
            poetry update
            poetry install
            poetry run python -c "from ecommerce_common.util import import_module_string"
            poetry run python -c "import blacksheep"
            poetry run python -c "import product"
            poetry run python -c "import settings"
      - name: build internal common package
        working-directory: services/common/python
        env:
            PIPENV_VENV_IN_PROJECT: 1
        run: |
            poetry run pip3 install build==1.2.2
            poetry run python -m build ./c_exts
      - name: install internal common package
        working-directory: services/product/v2
        run: |
            poetry run pip install  ../../common/python/c_exts/dist/my_c_extension_lib-0.0.2-cp312-cp312-linux_x86_64.whl
            poetry run python -c "from c_exts.util import keygen"

      - name: lint check
        working-directory: services/product/v2
        run: |
            poetry run ruff check ./src/ ./tests/ ./settings/

      - name: run tests
        working-directory: services/product/v2
        run: |
            ./run_test

