#!/bin/bash

mariadb --protocol=tcp --host=127.0.0.1 --port=3309 --user=root --password=$MARIADB_ROOT_PASSWORD <<-EOSQL
  REVOKE SELECT, INSERT, UPDATE, DELETE ON \`$DB_NAME\`.*  FROM  '$DB_APP_UNAME'@'%';
  REVOKE SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, GRANT OPTION ON \`$DB_NAME\`.* FROM '$SITEDBA_UNAME'@'localhost';
  REVOKE SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, GRANT OPTION ON \`$DB_NAME\`.* FROM '$SITEDBA_UNAME'@'$CONTAINER_IP_RANGE';
  DROP DATABASE \`$DB_NAME\`;
EOSOL
