"""add column for file size

Revision ID: 719b821e278a
Revises: da2eb9e7c659
Create Date: 2021-07-05 16:30:06.730406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '719b821e278a'
down_revision = 'da2eb9e7c659'
branch_labels = None
depends_on = None


def upgrade(is_offline, from_revision, to_revision, service_db, auth_url=None, sql_exe=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadedfile', sa.Column('mimetype_toplvl', sa.String(11), nullable=False))
    op.add_column('uploadedfile', sa.Column('mimetype_sub',    sa.String(9), nullable=False))
    op.add_column('uploadedfile', sa.Column('size', sa.Integer(), nullable=False))
    op.create_check_constraint(constraint_name='uploadedfile_size_positive_number_check',
            table_name='uploadedfile', condition = 'size > 0' )
    # ### end Alembic commands ###


def downgrade(is_offline, from_revision, to_revision, service_db, auth_url=None, sql_exe=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uploadedfile_size_positive_number_check', 'uploadedfile', type_='check')
    op.drop_column('uploadedfile', 'size')
    op.drop_column('uploadedfile', 'mimetype_toplvl')
    op.drop_column('uploadedfile', 'mimetype_sub')
    # ### end Alembic commands ###

