"""alter table columns and remove filereference

Revision ID: d6bff6abc5b7
Revises: 719b821e278a
Create Date: 2021-07-09 15:07:35.384790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6bff6abc5b7'
down_revision = '719b821e278a'
branch_labels = None
depends_on = None


def upgrade(is_offline, from_revision, to_revision, service_db, auth_url=None, sql_exe=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filereference')
    op.alter_column('fileaccesscontrollist', 'rd_flg',  existing_type=mysql.TINYINT(display_width=1),  nullable=False)
    op.alter_column('fileaccesscontrollist', 'rd_acl_flg', existing_type=mysql.TINYINT(display_width=1), nullable=False)
    op.drop_column('fileaccesscontrollist', 'wr_acl_flg')
    op.drop_column('fileaccesscontrollist', 'wr_flg')
    op.add_column('uploadedfile', sa.Column('uploader', sa.String(length=6), nullable=False))
    # ### end Alembic commands ###


def downgrade(is_offline, from_revision, to_revision, service_db, auth_url=None, sql_exe=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadedfile', 'uploader')
    op.add_column('fileaccesscontrollist', sa.Column('wr_flg', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('fileaccesscontrollist', sa.Column('wr_acl_flg', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('fileaccesscontrollist', 'rd_acl_flg',  existing_type=mysql.TINYINT(display_width=1),   nullable=True)
    op.alter_column('fileaccesscontrollist', 'rd_flg',  existing_type=mysql.TINYINT(display_width=1),  nullable=True)
    op.create_table('filereference',
        sa.Column('service_label', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
        sa.Column('file_hashed', sa.BINARY(length=20), nullable=False),
        sa.Column('file_dup', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['file_hashed', 'file_dup'], ['uploadedfile.hashed', 'uploadedfile.duplicate'], name='filereference_ibfk_1'),
        sa.PrimaryKeyConstraint('file_hashed', 'file_dup', 'service_label'),
        mysql_collate='utf8mb4_bin',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
